# Generated by Django 5.0.8 on 2024-11-18 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_subject_subject_unique_subject_in_institution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_in_institution',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='insititution',
            new_name='institution',
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('subject_code', 'institution'), name='unique_subject_in_institution'),
        ),
    ]
