# Generated by Django 5.0.8 on 2024-11-19 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0003_remove_subject_unique_subject_in_institution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classCount', models.IntegerField(default=1)),
                ('date', models.DateTimeField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('students', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attendance\\static\\attendance\\images\\download')),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancesession')),
            ],
        ),
    ]
