# Generated by Django 5.0.8 on 2024-11-19 20:57

import attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceimages',
            name='attendance_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='attendance.attendancesession'),
        ),
        migrations.AlterField(
            model_name='attendanceimages',
            name='image',
            field=models.ImageField(max_length=255, upload_to=attendance.models.upload_to),
        ),
    ]
